######################################################################
# Automatically generated by qmake (2.01a) Sun Jan 7 13:20:42 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h mx.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp mx.cpp
